"""Reference values used by the dashboard dropdowns."""

WELLS = [
    "TXNO-11",
    "TXNO-12",
    "TXNO-13",
    "OMJ-1",
    "OMJ-2",
    "HMD-3",
    "BRN-5",
]

RIGS = [
    "TP 184",
    "TP 185",
    "TP 212",
    "TP 216",
    "TP 227",
    "TP 236",
    "ENTP 14",
]

PHASES = [
    '36"',
    'Inter Phase 36" - 30"',
    'Inter Phase 36" - 28"',
    'Inter Phase 36" - 26"',
    '30"',
    'Inter Phase 30" - 28"',
    '28"',
    'Inter Phase 28" - 26"',
    'Inter Phase 28" - 24"',
    'Inter Phase 28" - 22"',
    '26"',
    'Inter Phase 26" - 17"1/2"',
    'Inter Phase 26" - 16"',
    'Inter Phase 24" - 17"1/2"',
    '22"',
    'Inter Phase 22" - 17"1/2"',
    'Inter Phase 22" - 16"',
    '17"1/2',
    'Inter Phase 17"1/2 - 12"1/4"',
    '16"',
    'Inter Phase 16" - 12"1/4"',
    '12"1/4',
    '12"1/4" Build Up Section',
    '12"1/4" Build Up - 8"1/2"',
    'Inter Phase 12"1/4 - 8"1/2"',
    '8"1/2',
    '8"1/2 Build Up Section',
    '8"1/2 Build Up - 6"',
    '8.375"',
    '6"',
    '6" Build Up Section',
    'Inter Phase 6" - 4"3/4"',
    'Inter Phase 6" - 3"3/4"',
    '4"3/4',
    '4"1/2',
    '3"3/4',
    "Completion",
    "Drill Out CMT",
    "Rig Move",
    "Workover",
    "Decompletion",
    "Flat Time",
    "Recertification",
]

ROTARY_SYSTEMS = [
    "Top drive",
    "Kelly",
]
DRILL_PIPES=[
    '5"1/2',
    "5",
    '3"1/2',
]

BHA=[
    "DRILLING BHA",
    "DIRECTIONAL BHA",
    "PACKED HOLE BHA",
    "PENDULUM BHA",
    "SEMI PACKED BHA",
    "SLICK BHA",
    "MILLING BHA",
    "CLEAN OUT BHA",
    "CORING BHA",
    "FISHING BHA",
    "Wiper Trip BHA",
    "SCRAPING BHA",
    "DST BHA",
    "PRODUCTION (LONG STRING) CSG",
    "OPEN END DP",
    "Cutter BHA",
    "Setting Tool BHA",
    "LOGGING STRING BHA",
    "EXTENTION BHA",
    "Dummy BHA",
    "SAFETY STRING CSG",
    "PDM PACKED BHA",
    "SLOTTED LINER",
    "REAMING BHA",
    "SIDETRACK BHA",
    "SUPER PACKED HOLE BHA",
    "VERTICAL BHA",
    "BRIDGE PLUG W/ CEMENT CAP",
    "CASING PATCH",
    "CEMENT RETAINER",
    "CEMENT RETAINER W/ CEMENT CAP",
    "CHEMICAL INJECTION LINE",
    "COIL TUBING",
    "CONTROL LINE",
    "FISH",
    "FRAC STRING",
    "HOT OIL STRING",
    "INTERMEDIATE CASING",
    "INTERMEDIATE LINER",
    "KILL STRING BHA",
    "MECHANICAL ITEM",
    "PACKER ASSEMBLY",
    "PACKER WITH TAIL",
    "PLUG BACK",
    "PRODUCTION LINER",
    "PRODUCTION STRING",
    "PRODUCTION TUBING",
    "PROTECTIVE LINER",
    "ROD STRING","SUCKER RODS",
    "TEMP. BRIDGE PLUG",
    "TIEBACK LINER",
    "TUBING ASSEMBLY",
    "TUBING STRING",
    "WIRELINE ITEM",
    "WORK STRING",
    "TIEBACK STRING",
    "SUSPENDED COLUMN",
    "RTTS BHA",
    "DRIFTING BHA",
    "PERFORATION BHA",
]
